### ISSUE TITLE
Compilation fails for newer ROOT versions

### ISSUE THREAD

**Issue by VinzenzBildstein** [cnatzke-TRIUMF/make_ggac_histograms#1]
I think this issue affect any version of ROOT from 6.24.00 on. The two lines 
```
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED TRUE)
```
in the CMakeLists.txt have to be removed, they force the use of c++11 when ROOT needs c++14 or newer. I don't know if there is a way to require the standard to be at least c++11 unless something else sets a higher standard (like root-config).

EDIT: another way of doing this might be to only require it if the installed ROOT version is less than 6.24.00

**Comment by cnatzke** [comment]
I fixed this in commit #28708ab81a9ed1c551613d0b4d188a80120d448c
